FROM node:18
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY package.json .
#RUN apk add --update --no-cache --virtual .gyp \
#        python3 \
#        make \
#        g++ \
#    && ln -sf python3 /usr/bin/python \
#    && npm install \
#    && npm install -g typescript  \
#    && apk del .gyp
RUN npm install \
    && npm install -g typescript

COPY scheduler.ts .
RUN tsc scheduler.ts

CMD node scheduler.js
